# Github Actions Node.js workflow
name: Test
on:
  pull_request:

jobs:
  pytest: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest